// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcFnCTk7uoTwSdY105ivXpAxnuNAnSOM',
    appId: '1:587466305508:web:c6bd66c97602a0b184e1f1',
    messagingSenderId: '587466305508',
    projectId: 'bmicalc-b4f70',
    authDomain: 'bmicalc-b4f70.firebaseapp.com',
    storageBucket: 'bmicalc-b4f70.appspot.com',
    measurementId: 'G-W2JL2CZ9D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwNpuypxWgmYNs8Bee9aA4sDAnCi_phQ',
    appId: '1:587466305508:android:59385c165b0739dd84e1f1',
    messagingSenderId: '587466305508',
    projectId: 'bmicalc-b4f70',
    storageBucket: 'bmicalc-b4f70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcmzKi4L5wbjkZkyt7NCtNNbK3EmCMUDg',
    appId: '1:587466305508:ios:4e4a7891ccafb77884e1f1',
    messagingSenderId: '587466305508',
    projectId: 'bmicalc-b4f70',
    storageBucket: 'bmicalc-b4f70.appspot.com',
    iosBundleId: 'com.example.bmiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcmzKi4L5wbjkZkyt7NCtNNbK3EmCMUDg',
    appId: '1:587466305508:ios:4e4a7891ccafb77884e1f1',
    messagingSenderId: '587466305508',
    projectId: 'bmicalc-b4f70',
    storageBucket: 'bmicalc-b4f70.appspot.com',
    iosBundleId: 'com.example.bmiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHcFnCTk7uoTwSdY105ivXpAxnuNAnSOM',
    appId: '1:587466305508:web:25dbd01c81b11e1884e1f1',
    messagingSenderId: '587466305508',
    projectId: 'bmicalc-b4f70',
    authDomain: 'bmicalc-b4f70.firebaseapp.com',
    storageBucket: 'bmicalc-b4f70.appspot.com',
    measurementId: 'G-6TF4CZDFB8',
  );

}